### ISSUE TITLE
Question: Memeory Requirement for tf.record conversion

### ISSUE THREAD

**Issue by BorisPolonsky** [dalab/end2end_neural_el#14]
When I execute the following command in a docker container, my process got killed. Sometimes it will pop out some python built in error indicating OOM.
`python -m preprocessing.prepro_util`

I'm running on a 16GB RAM computer, haven't look into the code carefully and I'm not sure how much memory will be needed in total for the current implementation. Could the authors provide the system specification for the experiments? Thanks.

**Comment by NikosKolitsas** [comment]
Actually all the preprocessing, postprocessing and evaluation code (except the training which was done on a gpu server) back then was run in an desktop with <= 16GB of RAM. In the prepro_util code only the  part that loads the word2vec embeddings should be somewhat demanding 
```
gensim.models.KeyedVectors.load_word2vec_format(
        config.base_folder+"data/basic_data/wordEmbeddings/Word2Vec/GoogleNews-vectors-negative300.bin", binary=True)
```
Maybe there is something in your docker configuration that you could adjust (hard memory limits?)

**Comment by BorisPolonsky** [comment]
> Actually all the preprocessing, postprocessing and evaluation code (except the training which was done on a gpu server) back then was run in an desktop with <= 16GB of RAM. In the prepro_util code only the part that loads the word2vec embeddings should be somewhat demanding
> 
> ```
> gensim.models.KeyedVectors.load_word2vec_format(
>         config.base_folder+"data/basic_data/wordEmbeddings/Word2Vec/GoogleNews-vectors-negative300.bin", binary=True)
> ```
> 
> Maybe there is something in your docker configuration that you could adjust (hard memory limits?)

Thanks for your reply, I managed to run the code with a 48GB desktop. I'll check the docker configuration later.
