### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by nyhDudu** [dalab/end2end_neural_el#18]
I would like to ask what the specific environment is when running this code, what is the python version, the operating system and the memory. Because I keep having coding problems during the operation. When I uploaded the dataset to the server, some file names were quoted

**Comment by NikosKolitsas** [comment]
I don't remember exactly which version of python I was using but I guess 3.6. Could you provide more information about the error that you are facing? i.e. when you execute which command specifically? Maybe also paste the error messages. For which dataset you have problems?

**Comment by nyhDudu** [comment]
Thank you, the previous problem seems to be a coding problem on my computer.
I want to ask why in the process of my reproduction, I first need to understand the output through print, but the dimensions and other dimensions of the output are all "?"
