### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by SeekPoint** [dalab/end2end_neural_el#2]
(.venv) mldl@ub1604:~/ub16_prj/end2end_neural_el/code$ python -m preprocessing.prepro_util
Namespace(calculate_stats=True, cand_ent_num=30, char_freq_thr=1, chunking='per_document', create_entity_universe=False, entity_extension=None, experiment_name='corefmerge', include_wikidumpRLTD=False, lowercase_p_e_m=False, lowercase_spans=False, max_mention_width=10, p_e_m_choice='yago', persons_coreference=True, persons_coreference_merge=True, word_freq_thr=1)
Processing dataset:  clueweb.txt
Processing dataset:  aida_dev.txt
Processing dataset:  aida_test.txt
Processing dataset:  wikipedia.txt
Processing dataset:  aida_train.txt
Processing dataset:  aquaint.txt
Processing dataset:  ace2004.txt
Processing dataset:  msnbc.txt
not_in_word2vec_cnt =  83402
all_words_cnt =  301418
some frequency statistics. The bins are [...) 
word  frequency histogram, edges:  [1, 2, 3, 6, 11, 21, 31, 51, 76, 101, 201, inf]
absolute values:         [8934 3671 4155 2258 1383  502  427  220  114  146  107]
absolute cumulative (right to left):     [21917 12983  9312  5157  2899  1516  1014   587   367   253   107]
probabilites cumulative (right to left): [1.         0.59237122 0.42487567 0.2352968  0.13227175 0.06917005
 0.04626546 0.02678286 0.01674499 0.01154355 0.00488206]
character  frequency histogram, edges:  [1, 6, 11, 21, 51, 101, 201, 501, 1001, 2001, inf]
absolute values:         [ 4  2  1  2  2  2  3  2  6 61]
absolute cumulative (right to left):     [85 81 79 78 76 74 72 69 67 61]
probabilites cumulative (right to left): [1.         0.95294118 0.92941176 0.91764706 0.89411765 0.87058824
 0.84705882 0.81176471 0.78823529 0.71764706]
datasets:  ['clueweb.txt', 'aida_dev.txt', 'aida_test.txt', 'wikipedia.txt', 'aida_train.txt', 'aquaint.txt', 'ace2004.txt', 'msnbc.txt']
load disambiguations. wall time: 0.0024797757466634113  minutes
disambiguations_errors:  0
load wiki_name_id_map. wall time: 0.10593472719192505  minutes
wiki_name_id_map_errors:  0
duplicate names:  0
duplicate ids:  0
duplicate_mentions_cnt:  16470
end of p_e_m reading. wall time: 2.491971739133199  minutes
p_e_m_errors:  0
incompatible_ent_ids:  0
load disambiguations. wall time: 0.0020069042841593427  minutes
disambiguations_errors:  0
load wiki_name_id_map. wall time: 0.10539611975351969  minutes
wiki_name_id_map_errors:  0
duplicate names:  0
duplicate ids:  0
persons not_found_cnt: 8261
words in vocabulary:  21918
characters in vocabulary:  86
processing file:  ../data/new_datasets/clueweb.txt
../data/new_datasets/clueweb.txt  chunker parsing errors:  0
max_mention_width_violations : 0
gt_misses 0
gm_misses 0
gm_this_file 0
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mldl/ub16_prj/end2end_neural_el/code/preprocessing/prepro_util.py", line 828, in <module>
    create_tfrecords()
  File "/home/mldl/ub16_prj/end2end_neural_el/code/preprocessing/prepro_util.py", line 637, in create_tfrecords
    tfrecords_generator.process(filepath=new_dataset_folder+file)
  File "/home/mldl/ub16_prj/end2end_neural_el/code/preprocessing/prepro_util.py", line 618, in process
    for sample in self._generator.process(filepath):
  File "/home/mldl/ub16_prj/end2end_neural_el/code/preprocessing/prepro_util.py", line 434, in process
    for sample in self._generator.process(filepath):
  File "/home/mldl/ub16_prj/end2end_neural_el/code/preprocessing/prepro_util.py", line 391, in _process_gmonly
    print("recall %     : ", (1 - (gm_misses+gt_misses)/gm_this_file)*100, " %")
ZeroDivisionError: division by zero

(.venv) mldl@ub1604:~/ub16_prj/end2end_neural_el/code$

**Comment by NikolaosKolitsas** [comment]
Solution: Re-download the data.zip 

Explanation: Actually in order to create the tfrecords files and train the model you can go directly to step 3 and execute the command "python -m preprocessing.prepro_util". 
The two previous commands take the original datasets and transform them to a new common format. However, the previous command (python -m preprocessing.prepro_other_datasets) is using the stanford word tokenizer and it expects to find it inside the data folder but unfortunately I had forgotten it include it inside. So it was creating empty datasets with nothing inside hence the division by zero.

**Comment by loveJasmine** [comment]
(end2end_neural_el_env) ub16hp@UB16HP:~/ub16_prj/end2end_neural_el/code$ python3 -m preprocessing.prepro_util
Namespace(calculate_stats=True, cand_ent_num=30, char_freq_thr=1, chunking='per_document', create_entity_universe=False, entity_extension=None, experiment_name='corefmerge', include_wikidumpRLTD=False, lowercase_p_e_m=False, lowercase_spans=False, max_mention_width=10, p_e_m_choice='yago', persons_coreference=True, persons_coreference_merge=True, word_freq_thr=1)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ub16hp/ub16_prj/end2end_neural_el/code/preprocessing/prepro_util.py", line 822, in <module>
    vocabularyCounter = VocabularyCounter()
  File "/home/ub16hp/ub16_prj/end2end_neural_el/code/preprocessing/prepro_util.py", line 18, in __init__
    import gensim
  File "/usr/local/lib/python3.5/dist-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/__init__.py", line 15, in <module>
    from .doc2vec import Doc2Vec  # noqa:F401
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/doc2vec.py", line 349, in <module>
    from gensim.models.doc2vec_corpusfile import (
  File "gensim/models/doc2vec_corpusfile.pyx", line 1, in init gensim.models.doc2vec_corpusfile
AttributeError: module 'gensim.models.doc2vec_inner' has no attribute '__pyx_capi__'
(end2end_neural_el_env) ub16hp@UB16HP:~/ub16_prj/end2end_neural_el/code$

**Comment by loveJasmine** [comment]
it works after reinstall gensim
